# Generated by Django 5.1.6 on 2025-02-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
