# Generated by Django 5.1.6 on 2025-02-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_statuschange'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_app.telegrambot')),
            ],
        ),
        migrations.DeleteModel(
            name='StatusChange',
        ),
    ]
