# Generated by Django 5.1.6 on 2025-02-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0004_telegrambotstatus_delete_statuschange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='is_running',
        ),
    ]
